### ISSUE TITLE
build.sh doesn't actually depict the compilation status of the program

### ISSUE THREAD

**Issue by vishalv971** [vishalv971/CompetitiveCoding#27]
So the crux of the program is to ensure the build.sh runs successfully, it doesn't capture the outcome of the run. 
Need to fix the same.

**Comment by pranjalkaler** [comment]
Should we also add some module to run unit tests or any tests we add in our code? Before merging it should run all the tests.

**Comment by vishalv971** [comment]
> Should we also add some module to run unit tests or any tests we add in our code? Before merging it should run all the tests.

No essentially we need to use make files for cpp and some other equivalent for java, perhaps gradle or something @SaumyaSachdev

**Comment by pranjalkaler** [comment]
https://github.com/vishalv971/CompetitiveCoding/pull/47/checks?check_run_id=1048191348

Build status from my last PR. Is this what we are missing? For testing purpose, we can try to raise PR with corrupt code, and see if this test fails.
